# Generated by Django 3.1.7 on 2021-03-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210317_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lead_subtitle',
            field=models.CharField(blank=True, help_text='Subheading under banner title', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Subtext under banner title', max_length=100),
        ),
    ]
